# Generated by Django 4.2.2 on 2023-08-21 14:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("polyedu", "0010_rename_ressource_ressourceexterne"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images/")),
            ],
            options={
                "verbose_name_plural": "Items Categories",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polyshop.itemcategory",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polyedu.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Items",
            },
        ),
    ]
