# Generated by Django 4.2.2 on 2023-08-20 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polyedu", "0004_exercices"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Exercices",
            new_name="Exercice",
        ),
    ]
