# Generated by Django 4.2.2 on 2023-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0005_rename_exercices_exercice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=75)),
                ("author_first_name", models.CharField(blank=True, max_length=75)),
                ("title", models.CharField(max_length=75)),
                ("url_link", models.CharField(blank=True, max_length=75)),
                ("date_creation", models.DateTimeField(blank=True)),
                ("date_consultation", models.DateTimeField(blank=True)),
                ("published_from", models.CharField(blank=True, max_length=100)),
                ("number_of_pages", models.IntegerField(blank=True)),
            ],
        ),
    ]
