# Generated by Django 4.2.2 on 2023-08-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0006_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url_link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
