# Generated by Django 4.2.2 on 2023-08-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0007_alter_source_url_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="author_first_name",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="date_consultation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="date_creation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="number_of_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="published_from",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="url_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
