# Generated by Django 4.2.2 on 2023-08-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0008_alter_source_author_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75)),
                ("desc", models.CharField(max_length=75)),
                ("url_link", models.CharField(blank=True, max_length=200, null=True)),
                ("date_creation", models.DateTimeField(blank=True, null=True)),
                ("date_consultation", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        default="Aucune catégorie de matière",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polyedu.category",
                    ),
                ),
            ],
        ),
    ]
