# Generated by Django 4.2.2 on 2023-08-21 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0009_ressource"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ressource",
            new_name="RessourceExterne",
        ),
    ]
