# Generated by Django 4.2.2 on 2023-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0010_rename_ressource_ressourceexterne"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
