# Generated by Django 4.2.2 on 2023-08-22 00:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polyedu", "0011_profile_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="desc",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="ressourceexterne",
            name="desc",
            field=models.CharField(max_length=275),
        ),
    ]
