# Generated by Django 4.2.2 on 2023-09-06 00:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polyedu", "0012_alter_article_body_alter_article_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="desc",
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("slug", models.SlugField(blank=True, max_length=400, unique=True)),
                (
                    "body",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        default="Aucune catégorie de matière",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polyedu.category",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="forum_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="forumpost",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
